language: objective-c # Give me OSX images!
install:
  - sw_vers -productVersion
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 2.3.1
  - nvm use 2.3.1
  - npm install -g npm@2.14.4
  - npm install || echo First NPM install failed && npm install # Fix electron-prebuilt failing on first install
before_script:
  - node -v
  - npm -v
script: npm test
os: osx
cache:
  directories:
    - node_modules
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
