language: objective-c # Give me OSX images!
before_install:
  - sw_vers -productVersion
  - brew update
  - brew install p7zip
install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 6.9.1 # Must match package.json
  - npm install -g npm@3.10.9 # Must match package.json
  - npm install || echo First NPM install failed && npm install # Fix electron-prebuilt failing on first install
before_script:
  - node -v
  - npm -v
script: npm run test-coverage
os: osx
cache:
  directories:
    - node_modules
after_success:
  - npm run coveralls
  # - npm run build-artifact
# addons:
  # s3_region: 'us-est-1'
  # artifacts:
    # paths:
    # - ./download.txt
