version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
os: Windows Server 2012 R2
install:
  - systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
  - ps: Install-Product node 6.9.1 # Must match package.json
  - npm install -g npm@3.10.9 # Must match package.json
  - npm install --arch=ia32 || Echo First NPM install failed && npm install --arch=ia32
  - node -v
  - npm -v
build: off
platform:
  - x86
  - x64
environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: QkxS7B6UiQysk6aWhKHQd+36lKw/6pvjC9+wF4v/2RiD5wvoWi0kZJFrHFKpvPOK
  GITHUB_TOKEN:
    secure: X/JCTitKeibH9uTyAKi7ED04LT0qACHJonHNCuHVnBHA/GQtsFeNQea21K6QrLYy
  AWS_ACCESS_KEY_ID:
    secure: P1wUZ+fj6LY/CPMc056wdy/DgcixRWbPKIZc1POLSs0=
  AWS_SECRET_ACCESS_KEY:
    secure: C6Pz9dkXEZKBeWG86sw/k1v2riAGCKifP7qdcjX8f3nSll7EUrkSUlQZVnXIatJl
test_script:
  - npm run test-coverage
  # - npm run build-artifact
on_success:
  - npm run coveralls
# artifacts:
  # - path: download.txt
    # name: Download Build (link within text file)
# cache:
#   - node_modules -> package.json
