version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Windows Server 2012 R2
install:
  - systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
  - ps: Install-Product node 2.3.1
  - npm install -g npm@2.14.4
  - npm install || Echo First NPM install failed && npm install
  - node -v
  - npm -v
build: off
platform:
  - x86
  - x64
environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: QkxS7B6UiQysk6aWhKHQd+36lKw/6pvjC9+wF4v/2RiD5wvoWi0kZJFrHFKpvPOK
  GITHUB_TOKEN:
    secure: X/JCTitKeibH9uTyAKi7ED04LT0qACHJonHNCuHVnBHA/GQtsFeNQea21K6QrLYy
test_script:
  - npm run appveyor
on_success:
  - '.\\coveralls.bat'
# cache:
#   - node_modules -> package.json
